name: First-Workflow

on:
  push:
    branches: [ master ]

jobs:
  First-Job:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Executing Tests
        run: mvn test
